//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TextFixture.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TEXTFIXTURE_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDB_BITMAPTRACTUP               133
#define IDR_GIFUP                       135
#define IDR_GIFUPMOVING                 137
#define IDR_GIFUPBACKMOVING             138
#define IDR_GIFDOWN                     139
#define IDR_GIFDOWNMOVING               140
#define IDR_GIFDOWNBACKMOVING           141
#define IDI_ICONRED                     142
#define IDI_ICONGREEN                   143
#define IDC_SLIDER_ACC                  1000
#define IDC_LIST_MSG                    1001
#define IDC_LIST_MSG_1                  1001
#define IDC_LIST_MSG_2                  1002
#define IDC_RADIO1                      1003
#define IDC_RADIO_NOR                   1003
#define IDC_RADIO2                      1004
#define IDC_RADIO_TRY                   1004
#define IDC_BUTTON2                     1005
#define IDC_BUTTON_ROUTE                1005
#define IDC_EDIT_SEPPD                  1006
#define IDC_EDIT_ACC                    1007
#define IDC_EDIT3                       1011
#define IDC_DIRECTOR                    1011
#define IDC_EDIT4                       1012
#define IDC_DISTANCE                    1012
#define IDC_LOGICS                      1013
#define IDC_COMBO_DIR                   1014
#define IDC_COMBO_DIR2                  1017
#define IDC_COMBO_MOVE                  1017
#define IDC_SERIALPORT                  1018
#define IDC_POSTION                     1019
#define IDC_RADIOHEAD                   1021
#define IDC_RADIOTRIAL                  1022
#define IDC_BUTTONRELAYALLWORK          1023
#define IDC_BUTTONRELAYALLFAIL          1024
#define IDC_CHECK1                      1025
#define IDC_CHECKFORBIDSTATUS           1026
#define IDC_NOPOWER                     1027
#define IDC_POWER                       1028
#define IDC_TRACKCODE                   1029
#define IDC_CHECKEB1                    1030
#define IDC_CHECKEB2                    1031
#define IDC_CHECKEBRESULT               1032
#define IDC_CHECKFSB1                   1033
#define IDC_CHECKFSB2                   1034
#define IDC_CHECKFSBRESULT              1035
#define IDC_CHECKRDER1                  1036
#define IDC_CHECKRDER2                  1037
#define IDC_CHECKRDERRUSULT             1038
#define IDC_CHECKLDER1                  1039
#define IDC_CHECKLDER2                  1040
#define IDC_CHECKLDERRESULT             1041
#define IDC_CHECKZVR1                   1042
#define IDC_CHECKZVR2                   1043
#define IDC_CHECKZVRRESULT              1044
#define IDC_CHECKFSBEBENABLE            1045
#define IDC_CHECKFSBENABLE              1046
#define IDC_CHECKTIR                    1047
#define IDC_EDIT1                       1050
#define IDC_EDITREADEROFFSET            1050
#define IDC_COMBOWHEEL                  1051
#define IDC_EDIT2                       1052
#define IDC_EDITSETV                    1052
#define IDC_EDIT5                       1053
#define IDC_EDITSETSTOP                 1053
#define IDC_ACCTIMES                    1054
#define IDC_CHECK2                      1055
#define IDC_CHECK3                      1056
#define IDC_CHECK4                      1057
#define IDC_CHECK5                      1058
#define IDC_CHECK6                      1059
#define IDC_CHECK7                      1060
#define IDC_CHECK8                      1061
#define IDC_CHECK9                      1062
#define IDC_CHECK10                     1063
#define IDC_CHECK11                     1064
#define IDC_CHECK12                     1065
#define IDC_CHECK13                     1066
#define IDC_CHECK14                     1067
#define IDC_CHECK15                     1068
#define IDC_CHECK16                     1069
#define IDC_CHECKATO                    1070
#define IDC_CHECKATP1                   1071
#define IDC_CHECKATP2                   1072
#define IDC_CHECKTECHOP                 1073
#define IDC_COMBO3                      1074
#define IDC_TRACKSELECT                 1074
#define IDC_COMBOCARRIERFREQUENCY       1075
#define IDC_COMBOCODEFREQUNCEY          1076
#define IDC_EDIT6                       1077
#define IDC_NPARP1                      1077
#define IDC_EDIT7                       1078
#define IDC_NPAPR2                      1078
#define IDC_EDIT8                       1079
#define IDC_PAPR1                       1079
#define IDC_EDIT9                       1080
#define IDC_PAPR2                       1080
#define IDC_EDIT10                      1081
#define IDC_CODECLEARANCE               1081
#define IDC_EDIT11                      1082
#define IDC_CODECLEARANCEDIS            1082
#define IDC_BUTTON1                     1083
#define IDC_SAVEINIDATA                 1083
#define IDC_EDITSTART                   1084
#define IDC_STATICPIC                   1085
#define IDC_NPARP1ID                    1086
#define IDC_NPARP2ID                    1087
#define IDC_NPARP1ID2                   1088
#define IDC_NPARP2ID2                   1089
#define IDC_APRSENDDISTANCE             1090
#define IDC_FRUSENDDISTANCE             1091
#define IDC_SAVEINIDATATOFILE           1092
#define IDC_READERPOWER                 1093
#define IDC_READERNOPOWER               1094
#define IDC_MSCOMM1                     1095
#define IDC_WORKSTATUS                  1096
#define IDC_READDISTANCE                1097
#define IDC_BEEP                        1098
#define IDC_CHANNEL                     1099
#define IDC_RESTRICTV                   1100
#define IDC_EDITSPEEDLIMIT              1101
#define IDC_HEALTH                      1102
#define IDC_RFR1                        1103
#define IDC_RFR2                        1104
#define IDC_TIRR                        1105
#define IDC_EUMR                        1106
#define IDC_BUTTONSETV                  1107
#define IDC_BUTTONAUTOSTOP              1108
#define IDC_BUTTONREADEROFFSET          1109
#define IDC_BUTTONSTART                 1110
#define IDC_BUTTONAPROFFSET             1111
#define IDC_BUTTONCODEOFFSET            1112
#define IDC_FIRSTBREAKTIME              1113
#define IDC_BUTTONLIMITV                1114
#define IDC_EDITANTENNA                 1115
#define IDC_BUTTONANTENNA               1116
#define IDC_FIRSTBREAKDISTANCE          1117
#define IDC_BREAKERROR                  1118
#define IDC_CLEAR                       1119
#define IDC_CARRAY1                     1119
#define IDC_SLIPBREAKTIME               1120
#define IDC_SLIPBREAKDISTANCE           1121
#define IDC_SECONDBREAKTIME             1122
#define IDC_SECONDBREAKDISTANCE         1123
#define IDC_CHECKTECHOP2                1124
#define IDC_CODE1                       1125
#define IDC_FSK1                        1126
#define IDC_TACHO1                      1127
#define IDC_FSK2                        1128
#define IDC_TACHO2                      1129
#define IDC_GAPS1                       1130
#define IDC_PERSENT                     1131
#define IDC_SENDCODEGAPS                1132
#define IDC_TACHOOVERHEAD               1133
#define IDC_GAPSMODE                    1134
#define IDC_GAPSTOPTIME                 1135
#define IDC_CARRAY2                     1136
#define IDC_CODE2                       1137
#define IDC_SEND                        1138
#define IDC_STATICCOM                   1139
#define IDC_STATICOMPM                  1140
#define IDC_STATICATPM                  1141
#define IDC_CHECKKEEPGAP                1143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
